version: "3.9"

services:

  nginx:
    build:
      context: .
      dockerfile: ./docker/nginx/Dockerfile
    image: nginx:alpine
    container_name: server
    hostname: server
    ports:
      - "8000:80"

  fastapi:
    build:
      context: .
      dockerfile: ./docker/fastapi_application/Dockerfile
    container_name: fastapi
    hostname: fastapi
    command: uvicorn app.main:first_app --host 0.0.0.0:8001
#    volumes:
#      - .:/app
    ports:
      - "8001:8001"

  django:
    build:
      context: .
      dockerfile: ./docker/django_application/Dockerfile
    container_name: django
    hostname: django
    command: python manage.py runserver 0.0.0.0:8002
    ports:
      - "8002:8002"
