version: "3.9"

services:

  nginx:
    build:
      context: .
      dockerfile: ./docker/nginx/Dockerfile
    image: nginx:alpine
    container_name: server
    hostname: server
    ports:
      - "8000:80"

  django:
    build:
      context: .
      dockerfile: ./docker/django_application/Dockerfile
    container_name: django
    hostname: django
    command: python manage.py runserver 0.0.0.0:8002
    ports:
      - "8002:8002"
